#!/bin/bash

build() {
	add_binary "/bin/openssl"
	add_runscript

}

help() {
	cat <<HELPEOF
Use this simple hook in combination with dm-crypt plain to decrypt your keyfile in initramfs before it is used by the encrypt hook.
HELPEOF
}

